version: '3.8'

services:
  quizhub-db:
    image: postgres:15-alpine
    container_name: quizhub-postgres
    environment:
      POSTGRES_DB: quiz_hub
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  quizhub-app:
    build: .
    container_name: quizhub-backend
    ports:
      - "8080:8080"
    depends_on:
      - quizhub-db
    environment:
      # Nối thẳng vào container quizhub-db
      DB_URL: jdbc:postgresql://quizhub-db:5432/quiz_hub
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
      # Biến Google OAuth2
      GOOGLE_CLIENT_ID: ${G_ID}
      GOOGLE_CLIENT_SECRET: ${G_SECRET}
      # Biến Mail
      SPRING_MAIL_USERNAME: ${MAIL_USER}
      SPRING_MAIL_PASSWORD: ${MAIL_PASS}
      # Biến JWT
      JWT_SECRET: ${JWT_SECRET}
    restart: unless-stopped

volumes:
  pg_data:
