spring:
  application:
    name: quiz-hub

  datasource:
    url: jdbc:postgresql://localhost:5432/quiz_hub
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
      encoding: UTF-8
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: "lamcong70@gmail.com"
    password: "pijgiugbmewvdbvu"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  jwt:
    secret: 6a2f8e1c4b7d9f3a5e2b8c1d4f7a9e3c6b2f8e1c4b7d9f3a5e2b8c1d4f7a9e3c
    expiration: 86400000 # 24 hours in milliseconds
